### ISSUE TITLE
Exception "org.atmosphere.wasync.transport.TransportNotSupported" at SAL start

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/scheduling-abstraction-layer#69]
`2024-01-26 08:16:57 07:16:57.919 [New I/O worker #1] WARN  com.ning.http.client.providers.netty.handler.WebSocketProtocol - onError {}
2024-01-26 08:16:57 org.atmosphere.wasync.transport.TransportNotSupported: null
2024-01-26 08:16:57     at org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived(WebSocketTransport.java:209) ~[wasync-2.1.7.jar:?]
2024-01-26 08:16:57     at com.ning.http.client.providers.netty.handler.WebSocketProtocol.handle(WebSocketProtocol.java:96) ~[async-http-client-1.9.40.jar:?]
2024-01-26 08:16:57     at com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88) ~[async-http-client-1.9.40.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:?]
2024-01-26 08:16:57     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
2024-01-26 08:16:57     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
2024-01-26 08:16:57     at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2024-01-26 08:16:57 07:16:57.946 [New I/O worker #1] ERROR org.atmosphere.wasync.transport.WebSocketTransport - WebSocket Handshake Failed`

**Comment by ankicabarisic** [comment]
this error is not blocking SAL from working fine
